# source "https://rubygems.org"

# gem "jekyll", "~> 3.8"
# gem "jekyll-sitemap", "~> 0.13"
# gem "jekyll-mentions", "~> 1.2"
# gem "jekyll-paginate", "~> 1.1"
# gem "jekyll-seo-tag", "~> 2.3"
# gem "jekyll-redirect-from", "~> 0.12"
# gem "jekyll-default-layout", "~> 0.1"
# gem "jekyll-feed", "~> 0.9"
# gem "jemoji", "~> 0.9"
# gem "jekyll-remote-theme", "~> 0.4.0"

source "https://rubygems.org"

gem "jekyll", "~> 4.1"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-mentions", "~> 1.6.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-seo-tag", "~> 2.6.1"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-commonmark", "~> 1.3.1"
gem "jekyll-include-cache", "~> 0.2"
gem "jemoji", "~> 0.12"
gem "jekyll-remote-theme", "~> 0.3"
gem 'jekyll-default-layout'
gem "webrick", "~> 1.7"
